// Code generated by protoc-gen-go.
// source: pkg/playsource/playsource_service.proto
// DO NOT EDIT!

/*
Package playsource is a generated protocol buffer package.

It is generated from these files:
	pkg/playsource/playsource_service.proto

It has these top-level messages:
	Song
	QueueSongRequest
	QueueSongResponse
	GetPlayingRequest
	GetPlayingResponse
	GetPlayHistoryRequest
	GetPlayHistoryResponse
*/
package playsource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Song struct {
	// Crowdsound song id.
	SongId int32 `protobuf:"varint,1,opt,name=song_id" json:"song_id,omitempty"`
	// Song name.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Song artists.
	Artists []string `protobuf:"bytes,3,rep,name=artists" json:"artists,omitempty"`
}

func (m *Song) Reset()                    { *m = Song{} }
func (m *Song) String() string            { return proto.CompactTextString(m) }
func (*Song) ProtoMessage()               {}
func (*Song) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type QueueSongRequest struct {
	Song *Song `protobuf:"bytes,1,opt,name=song" json:"song,omitempty"`
}

func (m *QueueSongRequest) Reset()                    { *m = QueueSongRequest{} }
func (m *QueueSongRequest) String() string            { return proto.CompactTextString(m) }
func (*QueueSongRequest) ProtoMessage()               {}
func (*QueueSongRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueueSongRequest) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

type QueueSongResponse struct {
	// The Crowdsound song in question.
	SongId int32 `protobuf:"varint,1,opt,name=song_id" json:"song_id,omitempty"`
	Queued bool  `protobuf:"varint,2,opt,name=queued" json:"queued,omitempty"`
	// Whether or not a song was found. Will always be true if queued == true.
	Found bool `protobuf:"varint,3,opt,name=found" json:"found,omitempty"`
	// Whether or not the song was finished.
	Finished bool `protobuf:"varint,4,opt,name=finished" json:"finished,omitempty"`
}

func (m *QueueSongResponse) Reset()                    { *m = QueueSongResponse{} }
func (m *QueueSongResponse) String() string            { return proto.CompactTextString(m) }
func (*QueueSongResponse) ProtoMessage()               {}
func (*QueueSongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetPlayingRequest struct {
}

func (m *GetPlayingRequest) Reset()                    { *m = GetPlayingRequest{} }
func (m *GetPlayingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPlayingRequest) ProtoMessage()               {}
func (*GetPlayingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetPlayingResponse struct {
	Song *Song `protobuf:"bytes,1,opt,name=song" json:"song,omitempty"`
}

func (m *GetPlayingResponse) Reset()                    { *m = GetPlayingResponse{} }
func (m *GetPlayingResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPlayingResponse) ProtoMessage()               {}
func (*GetPlayingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetPlayingResponse) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

type GetPlayHistoryRequest struct {
}

func (m *GetPlayHistoryRequest) Reset()                    { *m = GetPlayHistoryRequest{} }
func (m *GetPlayHistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPlayHistoryRequest) ProtoMessage()               {}
func (*GetPlayHistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetPlayHistoryResponse struct {
	Song *Song `protobuf:"bytes,1,opt,name=song" json:"song,omitempty"`
}

func (m *GetPlayHistoryResponse) Reset()                    { *m = GetPlayHistoryResponse{} }
func (m *GetPlayHistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPlayHistoryResponse) ProtoMessage()               {}
func (*GetPlayHistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetPlayHistoryResponse) GetSong() *Song {
	if m != nil {
		return m.Song
	}
	return nil
}

func init() {
	proto.RegisterType((*Song)(nil), "PlaySource.Song")
	proto.RegisterType((*QueueSongRequest)(nil), "PlaySource.QueueSongRequest")
	proto.RegisterType((*QueueSongResponse)(nil), "PlaySource.QueueSongResponse")
	proto.RegisterType((*GetPlayingRequest)(nil), "PlaySource.GetPlayingRequest")
	proto.RegisterType((*GetPlayingResponse)(nil), "PlaySource.GetPlayingResponse")
	proto.RegisterType((*GetPlayHistoryRequest)(nil), "PlaySource.GetPlayHistoryRequest")
	proto.RegisterType((*GetPlayHistoryResponse)(nil), "PlaySource.GetPlayHistoryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for PlaySource service

type PlaySourceClient interface {
	// QueueSong attempts to queue a song for the playsource service to play.
	// QueueSongResponse indicates whether or not the song was queued.
	QueueSong(ctx context.Context, opts ...grpc.CallOption) (PlaySource_QueueSongClient, error)
	// GetPlaying returns the currently playing song (if any).
	GetPlaying(ctx context.Context, in *GetPlayingRequest, opts ...grpc.CallOption) (*GetPlayingResponse, error)
	// GetPlayHistory returns songs that have been played since the service has been running.
	GetPlayHistory(ctx context.Context, in *GetPlayHistoryRequest, opts ...grpc.CallOption) (PlaySource_GetPlayHistoryClient, error)
}

type playSourceClient struct {
	cc *grpc.ClientConn
}

func NewPlaySourceClient(cc *grpc.ClientConn) PlaySourceClient {
	return &playSourceClient{cc}
}

func (c *playSourceClient) QueueSong(ctx context.Context, opts ...grpc.CallOption) (PlaySource_QueueSongClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlaySource_serviceDesc.Streams[0], c.cc, "/PlaySource.PlaySource/QueueSong", opts...)
	if err != nil {
		return nil, err
	}
	x := &playSourceQueueSongClient{stream}
	return x, nil
}

type PlaySource_QueueSongClient interface {
	Send(*QueueSongRequest) error
	Recv() (*QueueSongResponse, error)
	grpc.ClientStream
}

type playSourceQueueSongClient struct {
	grpc.ClientStream
}

func (x *playSourceQueueSongClient) Send(m *QueueSongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playSourceQueueSongClient) Recv() (*QueueSongResponse, error) {
	m := new(QueueSongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *playSourceClient) GetPlaying(ctx context.Context, in *GetPlayingRequest, opts ...grpc.CallOption) (*GetPlayingResponse, error) {
	out := new(GetPlayingResponse)
	err := grpc.Invoke(ctx, "/PlaySource.PlaySource/GetPlaying", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playSourceClient) GetPlayHistory(ctx context.Context, in *GetPlayHistoryRequest, opts ...grpc.CallOption) (PlaySource_GetPlayHistoryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlaySource_serviceDesc.Streams[1], c.cc, "/PlaySource.PlaySource/GetPlayHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &playSourceGetPlayHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlaySource_GetPlayHistoryClient interface {
	Recv() (*GetPlayHistoryResponse, error)
	grpc.ClientStream
}

type playSourceGetPlayHistoryClient struct {
	grpc.ClientStream
}

func (x *playSourceGetPlayHistoryClient) Recv() (*GetPlayHistoryResponse, error) {
	m := new(GetPlayHistoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PlaySource service

type PlaySourceServer interface {
	// QueueSong attempts to queue a song for the playsource service to play.
	// QueueSongResponse indicates whether or not the song was queued.
	QueueSong(PlaySource_QueueSongServer) error
	// GetPlaying returns the currently playing song (if any).
	GetPlaying(context.Context, *GetPlayingRequest) (*GetPlayingResponse, error)
	// GetPlayHistory returns songs that have been played since the service has been running.
	GetPlayHistory(*GetPlayHistoryRequest, PlaySource_GetPlayHistoryServer) error
}

func RegisterPlaySourceServer(s *grpc.Server, srv PlaySourceServer) {
	s.RegisterService(&_PlaySource_serviceDesc, srv)
}

func _PlaySource_QueueSong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlaySourceServer).QueueSong(&playSourceQueueSongServer{stream})
}

type PlaySource_QueueSongServer interface {
	Send(*QueueSongResponse) error
	Recv() (*QueueSongRequest, error)
	grpc.ServerStream
}

type playSourceQueueSongServer struct {
	grpc.ServerStream
}

func (x *playSourceQueueSongServer) Send(m *QueueSongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playSourceQueueSongServer) Recv() (*QueueSongRequest, error) {
	m := new(QueueSongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PlaySource_GetPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GetPlayingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(PlaySourceServer).GetPlaying(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _PlaySource_GetPlayHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPlayHistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlaySourceServer).GetPlayHistory(m, &playSourceGetPlayHistoryServer{stream})
}

type PlaySource_GetPlayHistoryServer interface {
	Send(*GetPlayHistoryResponse) error
	grpc.ServerStream
}

type playSourceGetPlayHistoryServer struct {
	grpc.ServerStream
}

func (x *playSourceGetPlayHistoryServer) Send(m *GetPlayHistoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PlaySource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PlaySource.PlaySource",
	HandlerType: (*PlaySourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaying",
			Handler:    _PlaySource_GetPlaying_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueueSong",
			Handler:       _PlaySource_QueueSong_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetPlayHistory",
			Handler:       _PlaySource_GetPlayHistory_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4f, 0xc2, 0x30,
	0x14, 0x77, 0x30, 0x10, 0x9e, 0x88, 0xf0, 0x8c, 0xba, 0x2c, 0x4a, 0xb0, 0x17, 0x77, 0x9a, 0x64,
	0x1a, 0xe3, 0xd9, 0x8b, 0x5e, 0x34, 0x2a, 0xf1, 0xa2, 0x07, 0x32, 0x59, 0xc1, 0x46, 0x5d, 0xc7,
	0xba, 0x99, 0xf0, 0x0d, 0xfc, 0xd8, 0xb6, 0x93, 0xb1, 0x0d, 0x44, 0x3d, 0x6d, 0xed, 0xef, 0x5f,
	0xdf, 0x2f, 0x0f, 0x8e, 0x82, 0xd7, 0xf1, 0x71, 0xf0, 0xe6, 0x4e, 0x05, 0x8f, 0xc3, 0x21, 0xcd,
	0xfd, 0x0e, 0x04, 0x0d, 0x3f, 0xd8, 0x90, 0xda, 0x41, 0xc8, 0x23, 0x8e, 0x70, 0x2b, 0x91, 0x7e,
	0x82, 0x90, 0x33, 0xd0, 0xfb, 0xdc, 0x1f, 0xe3, 0x16, 0xac, 0x0b, 0xf9, 0x1d, 0x30, 0xcf, 0xd0,
	0xba, 0x9a, 0x55, 0xc1, 0x06, 0xe8, 0xbe, 0xfb, 0x4e, 0x8d, 0x92, 0x3c, 0xd5, 0x15, 0xec, 0x86,
	0x11, 0x13, 0x91, 0x30, 0xca, 0xdd, 0xb2, 0x55, 0x27, 0x0e, 0xb4, 0xee, 0x62, 0x1a, 0x53, 0x25,
	0xbe, 0xa7, 0x93, 0x98, 0x8a, 0x08, 0x3b, 0xa0, 0x2b, 0x8f, 0xc4, 0x60, 0xc3, 0x69, 0xd9, 0x59,
	0x8c, 0xad, 0x68, 0xe4, 0x01, 0xda, 0x39, 0x8d, 0x08, 0xb8, 0x2f, 0xe8, 0x72, 0x70, 0x13, 0xaa,
	0x13, 0xc5, 0xf2, 0x92, 0xe8, 0x1a, 0x6e, 0x42, 0x65, 0xc4, 0x63, 0xdf, 0x93, 0xc1, 0xea, 0xd8,
	0x82, 0xda, 0x88, 0xf9, 0x4c, 0xbc, 0x48, 0x82, 0xae, 0x6e, 0xc8, 0x36, 0xb4, 0x2f, 0x69, 0xa4,
	0xc2, 0xd8, 0xfc, 0x2d, 0xe4, 0x14, 0x30, 0x7f, 0x39, 0x0b, 0xfb, 0xeb, 0x85, 0x7b, 0xb0, 0x33,
	0x53, 0x5d, 0xc9, 0x59, 0x79, 0x38, 0x4d, 0xed, 0xce, 0x61, 0x77, 0x11, 0xf8, 0x9f, 0xa5, 0xf3,
	0x59, 0x82, 0x5c, 0xdf, 0x78, 0x03, 0xf5, 0x79, 0x07, 0xb8, 0x9f, 0x67, 0x2f, 0xd6, 0x69, 0x1e,
	0xac, 0x40, 0xbf, 0x83, 0xc9, 0x9a, 0xa5, 0xf5, 0x34, 0xbc, 0x06, 0xc8, 0xe6, 0xc4, 0x82, 0x64,
	0xa9, 0x14, 0xb3, 0xb3, 0x0a, 0x4e, 0x2d, 0xf1, 0x09, 0x9a, 0xc5, 0x39, 0xf1, 0xf0, 0x07, 0x4d,
	0xb1, 0x1c, 0x93, 0xfc, 0x46, 0x49, 0xad, 0x7b, 0xda, 0x45, 0xe3, 0x11, 0xb2, 0x9d, 0x7c, 0xae,
	0x26, 0xcb, 0x78, 0xf2, 0x15, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x0e, 0x93, 0x2d, 0xb7, 0x02, 0x00,
	0x00,
}
